### ISSUE TITLE
num_rows error

### ISSUE THREAD

**Issue by kevthenondev** [rabzobi/load-sheddy#5]
Trying to get property 'num_rows' error appears twice

**Comment by kevthenondev** [comment]
ignore the line numbers - I made some unrelated (I promise) changes

![image](https://user-images.githubusercontent.com/34403826/49591579-b5fc6e80-f966-11e8-9779-dfd63c08d50d.png)

**Comment by rabzobi** [comment]
local error on your pc, will connect with teamviewer and try fix
